---
title: "Final Table"
author: "Lawrence Hsu"
date: "May 8, 2018"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RSQLite)
library(tidyverse)
library(splitstackshape)
library(shiny)
```



```{r,echo=FALSE}
extracellular_membrane_mediators_neg <- read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-6784160].tsv", encoding="UCS-2")

plasma_membrane_mediators_neg <- read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-6784160] (1).tsv")

extracellular_membrane_mediator_positive <- read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-6784160] (2).tsv")

plasma_membrane_mediators_positive <- read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-6784160] (3).tsv")

egfr_signaling<-read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-1643713].tsv")

vegf_signaling<-read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-194138].tsv")

total<-rbind(extracellular_membrane_mediator_positive,extracellular_membrane_mediators_neg, plasma_membrane_mediators_neg,plasma_membrane_mediators_positive)
total_inflame<-unique(total)

ingredient_targets_disease_drug.TCMID.v2.03 <- read.delim("C:/Users/lawre/OneDrive/Captstone Project/ingredient_targets_disease_drug-TCMID.v2.03/ingredient_targets_disease_drug-TCMID.v2.03.txt", header=FALSE)
ingredient_targets_disease_drug.modified<-ingredient_targets_disease_drug.TCMID.v2.03[complete.cases(ingredient_targets_disease_drug.TCMID.v2.03),]
ingredient_targets_disease_drug.modified.split<-cSplit(ingredient_targets_disease_drug.modified,'V5',';', direction='long')
complex_pathways<-read.delim("C:/Users/lawre/OneDrive/Captstone Project/UniProt2Reactome_All_Levels.txt",header=FALSE)

```

```{r,echo=FALSE}
test<-dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(test,'total_egfr',egfr_signaling)
dbWriteTable(test,'total_inflame',total)
dbWriteTable(test,'total_vegf',vegf_signaling)
dbWriteTable(test, 'disease_network',ingredient_targets_disease_drug.modified.split)
query<-"create table egfr_inner_join as select * from total_egfr t inner join disease_network d on t.Identifier=d.V3"
x<-dbGetQuery(test,query)

query<-"create table inflame_inner_join as select * from total_inflame t inner join disease_network d on t.Identifier=d.V3"
x<-dbGetQuery(test,query)

query<-"create table vegf_inner_join as select * from total_vegf t inner join disease_network d on t.Identifier=d.v3"
x<-dbGetQuery(test,query)

query<-"select * from inflame_inner_join order by V3"
x<-dbGetQuery(test,query)
t<-x%>% group_by(V3)%>% summarise(count=n())
dbWriteTable(test,'proteins_inflame',t)

query<-"select * from egfr_inner_join order by V3"
x<-dbGetQuery(test,query)
t<-x%>%group_by(V3)%>% summarise(count=n())
dbWriteTable(test,'proteins_egfr',t)

query<-"select * from vegf_inner_join order by V3"
x<-dbGetQuery(test,query)
t<-x%>%group_by(V3)%>%summarise(count=n())
dbWriteTable(test,'proteins_vegf',t)

dbWriteTable(test,'complex_path',complex_pathways)
```


Table sustaining proliferative signaling pathways
```{r}

query<-"create table uniprot_complex_egfr as select * from proteins_egfr t left outer join complex_path cp on t.V3=cp.V1"
y<-dbGetQuery(test,query)
query<-'select * from uniprot_complex_egfr'
xy<-dbGetQuery(test,query)
table.sustain<-xy[!(xy$V5!='TAS'),]
table.sustain<-table.sustain[(table.sustain$V1=='P00533'),]
table.sustain['hallmark']<-'sustaining proliferative signaling'
```

Table inflammation pathways
```{r}
query<-"create table uniprot_complex_inflame as select * from proteins_inflame t left outer join complex_path cp on t.V3=cp.V1"
y<-dbGetQuery(test,query)
query<-'select * from uniprot_complex_inflame'
xy<-dbGetQuery(test,query)
evidence.group<-xy%>% group_by(V3)%>%summarise(count=n())
evidence.group
table.inflammation<-xy[!(xy$V5!='TAS'),]
table.inflammation<-table.inflammation[(table.inflammation$V3=='P22301'),]
table.inflammation['hallmark']<-'inflammation'
```

Table inducing angiogensis
```{r}
query<-"create table uniprot_complex_vegf as select * from proteins_vegf t left outer join complex_path cp on t.V3=cp.V1"
y<-dbGetQuery(test,query)
query<-'select * from uniprot_complex_vegf'
xy<-dbGetQuery(test,query)
table.angiogenesis<-xy[!(xy$V5!='TAS'),]
table.angiogenesis<-table.angiogenesis[(table.angiogenesis$V3=='P35222'),]
table.angiogenesis['hallmark']<-'angiogenesis'
```

merged table and clean up
```{r}
table.inflammation1<-rbind(table.inflammation,table.angiogenesis,table.sustain)
table.inflammation1$V3<-"P22301"
table.sustain1<-rbind(table.inflammation,table.angiogenesis,table.sustain)
table.sustain1$V3<-"P00533"
table.angiogenesis1<-rbind(table.inflammation,table.angiogenesis,table.sustain)
table.angiogenesis1$V3<-'P35222'
merged.table<-rbind(table.inflammation1,table.angiogenesis1,table.sustain1)
merged.table$count<-NULL
merged.table$`V3:1`<-NULL
merged.table$V5<-NULL
merged.table$V6<-NULL
names(merged.table)<-c('uniprotidcompare','uniprotid','pathwayid','pathwayname','hallmark')
merged.table$isthere<-if_else(merged.table$uniprotidcompare!=merged.table$uniprotid,0,1)
merged.table[1:10,]
```
```{r}

merged.table$herbal_ingredient<-'tea_polyphenols,epigallocatechin_3-gallate,17beta-oestradiol,34-benezopyrene,beta-glucose,arsenic'
merged.table.split<-cSplit(merged.table,'herbal_ingredient',',',direction='long')
merged.table.split.corrected<-merged.table.split%>% mutate(herbal_ingredient=as.character(herbal_ingredient), herbal_ingredients=if_else(herbal_ingredient=='34-benezopyrene','3,4-benezopyrene',herbal_ingredient))
merged.table.split.corrected$herbal_ingredient<-NULL
merged.table.split.corrected
merged.table.split.corrected$isthere<-if_else(merged.table.split.corrected$hallmark=='inflammation'& merged.table.split.corrected$herbal_ingredients!='arsenic' &                                             merged.table.split.corrected$uniprotidcompare==merged.table.split.corrected$uniprotid , 1,0)

merged.table.split.corrected$isthere<-if_else(merged.table.split.corrected$hallmark=='sustaining proliferative signaling'& merged.table.split.corrected$herbal_ingredients=='beta-glucose' & merged.table.split.corrected$uniprotidcompare==merged.table.split.corrected$uniprotid,0,merged.table.split.corrected$isthere)

merged.table.split.corrected$isthere<-if_else(merged.table.split.corrected$hallmark=='sustaining proliferative signaling'& merged.table.split.corrected$herbal_ingredients!='beta-glucose' & merged.table.split.corrected$uniprotidcompare==merged.table.split.corrected$uniprotid,1,merged.table.split.corrected$isthere)

merged.table.split.corrected$isthere<-if_else(merged.table.split.corrected$hallmark=='angiogenesis'& merged.table.split.corrected$uniprotidcompare==merged.table.split.corrected$uniprotid,1,merged.table.split.corrected$isthere)

merged.table.split.corrected<-merged.table.split.corrected[!(merged.table.split.corrected$uniprotidcompare!=merged.table.split.corrected$uniprotid),]
merged.table.split.corrected$isthere<-factor(merged.table.split.corrected$isthere)

#fixing the hallmark for heatmap
merged.table.split.corrected$hallmark<-ifelse(merged.table.split.corrected$hallmark=='inflammation',1,merged.table.split.corrected$hallmark)
merged.table.split.corrected$hallmark<-ifelse(merged.table.split.corrected$hallmark=='angiogenesis',2,merged.table.split.corrected$hallmark)
merged.table.split.corrected$hallmark<-ifelse(merged.table.split.corrected$hallmark=='sustaining proliferative signaling',3,merged.table.split.corrected$hallmark)
merged.table.split.corrected$hallmark<-factor(merged.table.split.corrected$hallmark)


col.plot<-c('white','black')
x1<-ggplot(data=merged.table.split.corrected, aes(x=herbal_ingredients,pathwayname,fill=isthere,text=paste("hallmark: ",hallmark,"<br>","pathwayID: ",pathwayid)))+theme_bw()+geom_tile(color='gray',size=0.25)+labs(x='',y='')+theme(axis.text.x = element_text(angle = 20, hjust = 1, size=9))+ coord_fixed()+scale_y_discrete(expand=c(0,0))+scale_fill_manual(values=col.plot)
hallmarks<-c('inflammation','angiogenesis','sustaining proliferative signaling')

x2<-ggplot(data=merged.table.split.corrected,aes(pathwayname,hallmark,fill=hallmark))+geom_tile(color='gray')+theme(axis.text.y = element_blank())+scale_x_discrete(labels=hallmarks)
plotlyplot<-plotly::ggplotly(x1, width=1000, height=1000)
plotlyplot2<-plotly::ggplotly(x2, width=1000, height=1600)
plotlyplot
# fig=tools.make_subplots(rows=1, cols=2)
# merged.table.split.corrected$isthere<-as.numeric(merged.table.split.corrected$isthere)
# heatmaply(merged.table.split.corrected,Rowv=NULL,Colv="Rowv")
# 
# test4<-merged.table.split.corrected[c('pathwayname','hallmark','isthere','herbal_ingredients')]
# test5<-merged.table.split.corrected%>%spread(herbal_ingredients,isthere)
# test5$hallmark<-ifelse(test5$hallmark=='sustaining proliferative signaling',4,test5$hallmark)
# test5$hallmark<-ifelse(test5$hallmark=='inflammation',5,test5$hallmark)
# test5$hallmark<-ifelse(test5$hallmark=='angiogenesis',6,test5$hallmark)


```
