---
title: "Pathways_first_Pass"
author: "Lawrence Hsu"
date: "February 26, 2018"
output:
  word_document: default
  html_document: default
---
```{r}
library(RSQLite)
library(tidyverse)
library(splitstackshape)
```


A search on inflammatory response lead me to four different tables that fell into two categories: positive and negative regulation. Afecting the mediators on the extracellular membrane and plasma membrane. 
```{r,echo=FALSE}

extracellular_membrane_mediators_neg <- read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-6784160].tsv", encoding="UCS-2")

plasma_membrane_mediators_neg <- read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-6784160] (1).tsv")

extracellular_membrane_mediator_positive <- read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-6784160] (2).tsv")

plasma_membrane_mediators_positive <- read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-6784160] (3).tsv")

egfr_signaling<-read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-1643713].tsv")

vegf_signaling<-read.delim("C:/Users/lawre/Downloads/Participating Molecules [R-HSA-194138].tsv")

total<-rbind(extracellular_membrane_mediator_positive,extracellular_membrane_mediators_neg, plasma_membrane_mediators_neg,plasma_membrane_mediators_positive)
total_inflame<-unique(total)

ingredient_targets_disease_drug.TCMID.v2.03 <- read.delim("C:/Users/lawre/OneDrive/Captstone Project/ingredient_targets_disease_drug-TCMID.v2.03/ingredient_targets_disease_drug-TCMID.v2.03.txt", header=FALSE)
ingredient_targets_disease_drug.modified<-ingredient_targets_disease_drug.TCMID.v2.03[complete.cases(ingredient_targets_disease_drug.TCMID.v2.03),]
ingredient_targets_disease_drug.modified.split<-cSplit(ingredient_targets_disease_drug.modified,'V5',';', direction='long')
simple_pathways<-read.delim("C:/Users/lawre/OneDrive/Captstone Project/UniProt2Reactome.txt",header=FALSE)
complex_pathways<-read.delim("C:/Users/lawre/OneDrive/Captstone Project/UniProt2Reactome_All_Levels.txt",header=FALSE)
```

```{r}
test<-dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(test,'total_egfr',egfr_signaling)
dbWriteTable(test,'total_inflame',total)
dbWriteTable(test,'total_vegf',vegf_signaling)
dbWriteTable(test, 'disease_network',ingredient_targets_disease_drug.modified.split)
query<-"create table egfr_inner_join as select * from total_egfr t inner join disease_network d on t.Identifier=d.V3"
x<-dbGetQuery(test,query)

query<-"create table inflame_inner_join as select * from total_inflame t inner join disease_network d on t.Identifier=d.V3"
x<-dbGetQuery(test,query)

query<-"create table vegf_inner_join as select * from total_vegf t inner join disease_network d on t.Identifier=d.v3"
x<-dbGetQuery(test,query)

query<-"select * from inflame_inner_join order by V3"
x<-dbGetQuery(test,query)
t<-x%>% group_by(V3)%>% summarise(count=n())
dbWriteTable(test,'proteins_inflame',t)

query<-"select * from egfr_inner_join order by V3"
x<-dbGetQuery(test,query)
t<-x%>%group_by(V3)%>% summarise(count=n())
dbWriteTable(test,'proteins_egfr',t)

query<-"select * from vegf_inner_join order by V3"
x<-dbGetQuery(test,query)
t<-x%>%group_by(V3)%>%summarise(count=n())
dbWriteTable(test,'proteins_vegf',t)

dbWriteTable(test,'simple_path',simple_pathways)
dbWriteTable(test,'complex_path',complex_pathways)
```


<!-- ```{r,echo=FALSE} -->
<!-- query<-"create table path_to_protein_outer_join as select * from total_egfr t left outer join disease_network d on t.Identifier=d.V3" -->
<!-- x<-dbGetQuery(test,query) -->

<!-- query<-"select * from path_to_protein_inner_join p order by V3" -->
<!-- x<-dbGetQuery(test,query) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- #experiment with seeing what components actually are being mapped only 5... -->
<!-- t<-x%>% group_by(V3)%>% summarise(n=n()) -->

<!-- #testing if there are matches but being removed due to blank fields -->
<!-- query<-"select * from path_to_protein_outer_join p order by V3" -->
<!-- x<-dbGetQuery(test,query) -->
<!-- unique<-x%>% group_by(V3)%>% rename(uniprot=V3)%>% summarise(count=n()) -->
<!-- unique -->

<!-- #no difference between left outer and inner join. Made a new table with only distinct proteins matched -->
<!-- dbWriteTable(test,'proteins',t) -->

<!-- ``` -->

Table sustaining proliferative signaling pathways
```{r}

query<-"create table uniprot_complex_egfr as select * from proteins_egfr t left outer join complex_path cp on t.V3=cp.V1"
y<-dbGetQuery(test,query)
query<-'select * from uniprot_complex_egfr'
xy<-dbGetQuery(test,query)
table.sustain<-xy[!(xy$V5!='TAS'),]
table.sustain<-table.sustain[(table.sustain$V3=='P00533'),]
unique.pathway.complex.group<-xy%>% group_by(V3)%>%summarise(count=n())
# 462 unique pathways (complex) 
unique.pathway.complex.group
```


summary of inflammatory pathways
```{r}
query<-"select V3 as Uniprot, count from proteins_inflame order by count desc"
dbGetQuery(test,query)

query<-"create table uniprot_simple_inflame as select * from proteins_inflame t left outer join simple_path sp on t.V3=sp.V1"
y<-dbGetQuery(test,query)
query<-'select * from uniprot_simple_inflame'
xy<-dbGetQuery(test,query)

#14 distinct pathways (simple) 
uni_simple_pathway<-xy%>% group_by(V4) %>% rename(simple_pathways=V4) %>% summarise(count=n())
uni_simple_pathway

query<-"create table uniprot_complex_inflame as select * from proteins_inflame t left outer join complex_path cp on t.V3=cp.V1"
y<-dbGetQuery(test,query)
query<-'select * from uniprot_complex_inflame'
xy<-dbGetQuery(test,query)

unique.pathway.complex.group<-xy%>% group_by(V4)%>% rename(complex_pathways=V4) %>%summarise(count=n())
# 22 unique pathways (complex)
unique.pathway.complex.group

```

Summary of inducing angiogensis pathways
```{r}
query<-"select V3 as uniprot, count from proteins_vegf order by count desc"
dbGetQuery(test,query)

query<-"create table uniprot_simple_vegf as select * from proteins_vegf t left outer join simple_path sp on t.V3=sp.V1"
y<-dbGetQuery(test,query)
query<-'select * from uniprot_simple_vegf'
xy<-dbGetQuery(test,query)

#151 distinct pathways (simple) 
uni_simple_pathway<-xy%>% group_by(V4) %>% rename(simple_pathways=V4) %>% summarise(count=n())
uni_simple_pathway

query<-"create table uniprot_complex_vegf as select * from proteins_vegf t left outer join complex_path cp on t.V3=cp.V1"
y<-dbGetQuery(test,query)
query<-'select * from uniprot_complex_vegf'
xy<-dbGetQuery(test,query)

unique.pathway.complex.group<-xy%>% group_by(V4)%>% rename(complex_pathways=V4) %>%summarise(count=n())
# 290 unique pathways (complex)
unique.pathway.complex.group
```

